version: '3.9'
services:
  jenkins:
    image: djangoreactdev/jenkins
    container_name: jenkins
    ports:
      - 8080:8080
    volumes:
      - /mnt/sdf/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock